directories:
  stored_csv_xlsx_directory: ../data
  persist_directory: ../data/chroma

google_ai_config:
  GOOGLE_API_KEY: 'AIzaSyDzYEtOw-rxGSj_bKcR1QkSW9NeWL0k_UA'

llm_configs:
  model_pretrain: 'FreedomIntelligence/DiagnosisGPT-6B' 
  max_tokens: 1024
  temperature: 0.6
  top_p: 0.9

rag_config:
  collection_name: patient_medical_information
  top_k: 1